language: node_js
node_js:
- '8'
dist: trusty
services:
- mongodb
- redis-server
env:
- NODE_ENV=ci
cache:
  directories:
  - node_modules
  - client/node_modules
install:
- npm install
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: C9PIUzZIkl5zFJDznk3G64+HlOvsn8hoOfQg02n8PMq8Jmx9JajMZFPLAz90c3yBui8DPNSK+mUYDX/qJfAvX2C2jslyh4QxV2KMVUZ8iUNsZolpxUzkEY0BBiqAVu7nEQGoYffsG8XaCjttimli1drnVJQMilD7Q+3Gm2/rF1afIVELTF+YY3Y4afPBLuX/fHGzDIxStjIlbJF+6aa6N5gZoUQYqwSEilbZDa78bbH/LfRVRsv4V7BKxjOjTFIaKAlDGsZyCFSx2kJ31IWNCoLbBffp6GadV1xN1AkFCLoWYkzD9hBx8+ylYrchX4oz0pOQfPcXn/b5KTvt9E4saok2EgTlks696+D1CnXaB1JK2JedoIkilSUpCH1iniKb+BgLchby04NyaPPNWt+9qC4oSlmrqJF+l626QM4M/SkhUwjNaioEhskVdM0ZFiGDw46yQ0IAKAVkCm78ThdBQbPGayV3C67mOHySpEpXe+4zU8hcaPxrLn9nPMj+XJm4lO4gaPmfAROS7RndGFO/45C6/IsSoopZl5dKRTqklRm0b4cPAhjNE6OZDtjrIaPub2GlrCtW3l2K1oepybXtG856V+fXwPnornMomdVu7sjCOSacEHTILpXrfPP0enGaftFIzvAt9VLJO2CXib9e0/13UWbSpMIosFdE19/pG20=
