export const ActionTypes = {
    FETCH_USER: 'FETCH_USER',
    FETCH_TASKS: 'FETCH_TASKS',
    NEW_TASK: 'NEW_TASK',
    DELETE_TASK: 'DELETE_TASK',
    TASK_PATCHED: 'TASK_PATCHED',
    TASK_CHECKED: 'TASK_CHECKED'
};
