export const ActionTypes = {
    FETCH_USER: 'FETCH_USER',
    FETCH_TODOS: 'FETCH_TODOS',
    NEW_TODO: 'NEW_TODO',
    DELETE_TODO: 'DELETE_TODO',
    TODO_PATCHED: 'TODO_PATCHED',
    TODO_CHECKED: 'TODO_CHECKED'
};
